### ISSUE TITLE
Larger icon if state hidden

### ISSUE THREAD

**Issue by mouth4war** [mattieha/slider-button-card#34]
**Is your feature request related to a problem? Please describe.**
Icon size is a little small for older eyes.

**Describe the solution you'd like**
Can icon take up full height if state is hidden?

**Describe alternatives you've considered**
None

**Comment by mattieha** [comment]
I understand your feature request, but I guess this is not for everyone, so I will not implement this by default.
That said there is an easy way to enlarge the icon size (per card).

Make sure you have installed the awesome [Card mod](https://github.com/thomasloven/lovelace-card-mod) plugin.
After that you add this to the card config in yaml:
```
  style: |
    ha-card {
      --mdc-icon-size: 3em !important;
    }
```

![image](https://user-images.githubusercontent.com/3931195/122587522-3505ae00-d05e-11eb-8b2e-56ed8b8e2fb9.png)
Left: 3em | Right 2.2em (default for this card)

Don't forget the `!important` part otherwise it won't work.
Downside is that you have to add this for every Slider button card.

Hope this helps you.

**Comment by mouth4war** [comment]
Thanks! How about a compact mode of half height instead? I find the sliders
quite thick for just lights/fans.

**Comment by mattieha** [comment]
@mouth4war I've made a compact mode:  #68 , looking forward about your feedback.

**Comment by mouth4war** [comment]
It's brilliant
