### ISSUE TITLE
Using slider when light off doesn't set brightness

### ISSUE THREAD

**Issue by mouth4war** [mattieha/slider-button-card#35]
**Checklist:**

- [* ] I updated to the latest version available
- [* ] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**

**Browser and Operating System:**

**Description of problem:**

When sliding on a light that is off, the brightness should be set but currently it only turns the light on.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by KairuByte** [comment]
I'm not able to replicate this on the latest beta with an iOS device, so this may already be corrected.

**Comment by mattieha** [comment]
I can't reproduce this as well. Can you test with the new v1.4.0 version if the problem still exists?

**Comment by Reynders1** [comment]
> I can't reproduce this as well. Can you test with the new v1.4.0 version if the problem still exists?

Good morning,
I have exactly the same problem on MacOS BigSure with both Safari and Chrome.
I also have the following error message since update to 1.4.0:

Logger: frontend.js.latest.202106030
Source: components/system_log/__init__.py:190 
First occurred: 9:52:32 (7 occurrences) 
Last logged: 10:08:35

http://homeassistant.local:8123/hacsfiles/slider-button-card/slider-button-card.js:200:19530 TypeError: undefined is not an object (evaluating 't[e[0]]=i')
http://homeassistant.local:8123/hacsfiles/slider-button-card/slider-button-card.js:200:19536 Uncaught TypeError: Cannot set property 'icon' of undefined
:0:0 Script error.

Christian

**Comment by mattieha** [comment]
@Reynders1 What version did you previously had installed (where the bug doesn't exists).

**Comment by Reynders1** [comment]
@mattieha I can't tell, but it's the one that was available through HACS 2 days ago.
The behaviour of the slider is weird now. The I try to move it to switch on a lamp (coming from the HUE integration),  the status remains OFF all the time, even if the spinning around the on/off button is running.

**Comment by mattieha** [comment]
@Reynders1 Hmm strange, I'll try to fix it this weekend, if you wan't a working version now you should uninstall and install v1.2.0

**Comment by mouth4war** [comment]
Like like the adaptive lighting custom compenent is causing trouble. When I turn it off, slider works fine.

The default Lovelace light card doesn't do this, though. It works the same whether adaptive lighting is on or off.

**Comment by Reynders1** [comment]
@mattieha I just tested version 1.5.1 and it's looking much better now. Sliding seems to be properly working. The visual editor is updating the config, with the exception of the section "action button" where no changes are reflected. When changing e.g.the mode  to e.g. "toggle", the option to save the configuration card does not show up. It stays to "Close".
Apart from that, it looks great! Well done!!
